### ISSUE TITLE
numpy missing

### ISSUE THREAD

**Issue by Woile** [rmst/yoke#1]
I'm getting this error, I think numpy is missing

```python
Traceback (most recent call last):
  File "/usr/local/bin/yoke", line 2, in <module>
    import yoke
  File "/usr/local/lib/python3.6/dist-packages/yoke/__init__.py", line 1, in <module>
    from yoke.service import Device, Service, GAMEPAD_EVENTS, EVENTS
  File "/usr/local/lib/python3.6/dist-packages/yoke/service.py", line 12, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

**Comment by rmst** [comment]
Oups, thanks. Fixed.
