### ISSUE TITLE
Yoke OSError when executed on Manjaro

### ISSUE THREAD

**Issue by wonbinbk** [rmst/yoke#10]
I have followed all the steps on the Github readme. I added a new group and added my self to it per yoke-enable-uinput script, with some modifications because the command to add groups and users is not for Arch. Anyway I got the group "uinput" added and I added myself to that group then make the udev rules. Command "yoke" or "sudo yoke" or "sudo /bin/yoke" produce the same error below:

`Traceback (most recent call last):
  File "/bin/yoke", line 42, in <module>
    dev = yoke.Device(args.name, events=Service.events)
  File "/usr/lib/python3.7/site-packages/yoke/service.py", line 67, in __init__
    self.device = uinput.Device(events, name, BUS_VIRTUAL)
  File "/usr/lib/python3.7/site-packages/uinput/__init__.py", line 178, in __init__
    self.__uinput_fd = fd or fdopen()
  File "/usr/lib/python3.7/site-packages/uinput/__init__.py", line 84, in fdopen
    return _libsuinput.suinput_open()
  File "/usr/lib/python3.7/site-packages/uinput/__init__.py", line 70, in _open_error_handler
    raise OSError(code, msg)
OSError: [Errno 19] Failed to open the uinput device: No such device`

**Comment by rmst** [comment]
Have you tried https://stackoverflow.com/questions/48640935/oserror-errno-19-failed-to-open-the-uinput-device-no-such-device?rq=1 ?

**Comment by wonbinbk** [comment]
Thank you!
It works now.
So my problem was uinput was not probed.
