### ISSUE TITLE
Can't run on Windows 10

### ISSUE THREAD

**Issue by iRomanyshyn** [rmst/yoke#13]
Hi! When I try to run it on Windows 10 as Administrator, I get error:

`C:\Program Files\Python37\Scripts>python yoke
Traceback (most recent call last):
  File "yoke", line 79, in <module>
    dev = yoke.Device(args.name, events=Service.events)
  File "C:\Program Files\Python37\lib\site-packages\yoke\service.py", line 100, in __init__
    self.device = VjoyDevice(1)
  File "C:\Program Files\Python37\lib\site-packages\yoke\vjoy\vjoydevice.py", line 32, in __init__
    self.lib = cdll.LoadLibrary(lib_path)
  File "C:\Program Files\Python37\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Program Files\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found`

Please, help, I want to try it! :)

**Comment by rmst** [comment]
Hm, did you install the vJoy driver version 2.1.8 ?

**Comment by rmst** [comment]
Does any of this https://stackoverflow.com/questions/1940578/windowserror-error-126-the-specified-module-could-not-be-found solve your issue?

**Comment by rmst** [comment]
Closing due to inactivity.

**Comment by benkuly** [comment]
Same problem here. Latest vJoy installed.

**Comment by benkuly** [comment]
Changed line 32 of vjoydevice.py to
`lib_path = "c:\\Program Files\\vJoy\\x64\\vJoyInterface.dll"`
works.

**Comment by rmst** [comment]
What would be a reliable way of detecting the path to the system-wide DLL? Should we have a environment variable and assume `lib_path = "c:\\Program Files\\vJoy\\x64\\vJoyInterface.dll"` otherwise?

**Comment by medape** [comment]
The most reliable way to detect the system-wide DLL would be to read the registry via Python using [this StackOverflow question](https://stackoverflow.com/questions/16452540/registry-path-to-find-all-the-installed-applications) as a reference. Apparently the path must be within a folder within one of these two keys:

```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall
```

However, now that vJoy's app is stable and Yoke has code to work in any Windows from 7 onwards (and I have plans to reduce message size and thus latency further), I think this issue should be closed.
