### ISSUE TITLE
Yoke Crash on Startup

### ISSUE THREAD

**Issue by ellietheoracle** [rmst/yoke#50]
```
Starting service... Press Ctrl+C to exit.
Shutting down...
Traceback (most recent call last):
  File "/usr/local/bin/yoke", line 85, in <module>
    service.run()
  File "/usr/local/lib/python3.8/site-packages/yoke/service.py", line 162, in run
    zeroconf.register_service(self.info, ttl=10)
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2385, in register_service
    self._broadcast_service(info)
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2425, in _broadcast_service
    DNSText(info.name, _TYPE_TXT, _CLASS_IN | _CLASS_UNIQUE, info.other_ttl, info.text), 0
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 613, in __init__
    assert isinstance(text, (bytes, type(None)))
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yoke", line 90, in <module>
    service.close()
  File "/usr/local/lib/python3.8/site-packages/yoke/service.py", line 213, in close
    zeroconf.unregister_service(self.info)
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2469, in unregister_service
    out.add_answer_at_time(DNSText(info.name, _TYPE_TXT, _CLASS_IN | _CLASS_UNIQUE, 0, info.text), 0)
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 613, in __init__
    assert isinstance(text, (bytes, type(None)))
AssertionError
```

installed with pip3, ran the yoke-enable-uinput script

Fedora 32

**Comment by pzmarzly** [comment]
Should be fixed by #51 .

**Comment by ellietheoracle** [comment]
can i update through pip, or will i have to clone it ?

**Comment by pzmarzly** [comment]
I decided to merge #51 for now, so you can install it "normally" as described in https://github.com/rmst/yoke/blob/master/WEBVIEW.md (of course if you have the repo already cloned, you can just `git pull`).

Please note that I made the change for the "upcoming" 0.2 version. The current README is for v0.1, Google Play and F-Droid both contain Yoke v0.1.

BTW now that the 0.1 version is broken, it's a good time to finally release v0.2 @rmst
