### ISSUE TITLE
Crash after establishing connection to android

### ISSUE THREAD

**Issue by hochmax** [rmst/yoke#54]
System:
ubuntu 20.04
android 10

after connecting from the phone, following console output appears, the float values varying each time:

`Checking files on webserver… OK.
Writing manifest… OK.
Starting webserver on  42245 /home/hochmax/.local/lib/python3.8/site-packages/yoke/assets/joypad

To connect select "ROSguide-Yoke-1" on your device,
or connect manually to "192.168.43.130:42245"
Press Ctrl+C to exit.
Connected to  ('192.168.43.1', 35039)
Shutting down…
Traceback (most recent call last):
  File "/home/hochmax/.local/lib/python3.8/site-packages/yoke/service.py", line 364, in run
    v = self.preprocess(m, len(self.dev.events))
  File "/home/hochmax/.local/lib/python3.8/site-packages/yoke/service.py", line 288, in preprocess
    v = tuple([int(m) for m in v])
  File "/home/hochmax/.local/lib/python3.8/site-packages/yoke/service.py", line 288, in <listcomp>
    v = tuple([int(m) for m in v])
ValueError: invalid literal for int() with base 10: b' 8.0252 -0.36389998 5.6243 0.0 0.0 0.0 0.0'`

**Comment by hochmax** [comment]
I resolved it by installing the github apk instead of google play. Works like a charm, thank you very much for developing this.
