### ISSUE TITLE
Failed to open the uinput device: No such device 

### ISSUE THREAD

**Issue by virusz4274** [rmst/yoke#60]
Followed instruction on Raspberry pi OS with everything updated on a Raspberry Pi 4
when running yoke, getting this

          Traceback (most recent call last):
            File "/home/virusz4274/.local/bin/yoke", line 80, in <module>
              dev = yoke.Device(args.id, args.name, events=Service.events)
            File "/home/virusz4274/.local/lib/python3.7/site-packages/yoke/service.py", line 73, in __init__
              self.device = uinput.Device(events, name, BUS_VIRTUAL)
            File "/home/virusz4274/.local/lib/python3.7/site-packages/uinput/__init__.py", line 178, in __init__
              self.__uinput_fd = fd or fdopen()
            File "/home/virusz4274/.local/lib/python3.7/site-packages/uinput/__init__.py", line 84, in fdopen
              return _libsuinput.suinput_open()
            File "/home/virusz4274/.local/lib/python3.7/site-packages/uinput/__init__.py", line 70, in _open_error_handler
              raise OSError(code, msg)
          OSError: [Errno 19] Failed to open the uinput device: No such device

**Comment by nikty** [comment]
Try doing this as root:

```
# modprobe uinput
# chmod a+r+w /dev/uinput
```

**Comment by Caitex212** [comment]
Hey, I got the same error but the command didn't help.
