### ISSUE TITLE
AttributeError: 'int' object has no attribute 'items'

### ISSUE THREAD

**Issue by haltosan** [rmst/yoke#64]
Here's the output when I run it on my system.
```
$ yoke --id 1
Starting service... Press Ctrl+C to exit.
Shutting down...
Traceback (most recent call last):
  File "/usr/local/bin/yoke", line 85, in <module>
    service.run()
  File "/home/haltosan/.local/lib/python3.10/site-packages/yoke/service.py", line 161, in run
    self.info = ServiceInfo(stype, fullname, socket.inet_aton(adr), port, 0, 0, {}, fullname)
  File "/home/haltosan/.local/lib/python3.10/site-packages/zeroconf/_services/info.py", line 143, in __init__
    self._set_properties(properties)
  File "/home/haltosan/.local/lib/python3.10/site-packages/zeroconf/_services/info.py", line 241, in _set_properties
    for key, value in properties.items():
AttributeError: 'int' object has no attribute 'items'
```

I'm running Ubuntu 22.04, python3.10, pip 22.0.2. I ran the pip install command in the readme. I also ran the `yoke-enable-uinput` executable.

**Comment by joradom** [comment]
same to me ...

**Comment by joradom** [comment]
update: Tested the new version Yoke Webview and it works ...
os: kubuntu 20.04
phone: Huawei RIO-L01 
andoid 6.0.1

just wondering how to make a layout for flightgear now.

**Comment by non-resistant** [comment]
> update: Tested the new version Yoke Webview and it works ... os: kubuntu 20.04 phone: Huawei RIO-L01 andoid 6.0.1
> 
> just wondering how to make a layout for flightgear now.

@joradom How did switch to new version of Yoke Webview (which is android app) changed behavior of yoke (which is desktop app)?
