### ISSUE TITLE
I got error when run "yoke.py" in bin folder

### ISSUE THREAD

**Issue by alr86** [rmst/yoke#67]
every run "yoke.py" in the bin folder said:
```
Traceback (most recent call last):
  File "/home/alr86/.local/lib/python3.11/site-packages/yoke/./yoke", line 2, in <module>
    import yoke
  File "/home/alr86/.local/lib/python3.11/site-packages/yoke/__init__.py", line 1, in <module>
    from yoke.service import Device, Service, EVENTS
  File "/home/alr86/.local/lib/python3.11/site-packages/yoke/service.py", line 13, in <module>
    import uinput
  File "/home/alr86/.local/lib/python3.11/site-packages/uinput/__init__.py", line 86, in <module>
    _libsuinput_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "_libsuinput" + sysconfig.get_config_var("SO")))
                                                                                     ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

```

**Comment by ajburley** [comment]
I get the same, even after pip installing and trying to run from the installed location.

It seems to be due to this issue tuomasjjrasanen/python-uinput#44

Due to that issue, running python-uinput in Python 3.11 or above will fail. So yoke will fail also.

There is a fork of python-uinput mentioned in the comments of the above linked issue. So I guess yoke should be updated to use that fork instead, and the issue would be fixed.
