### ISSUE TITLE
Failed to open the uinput device: Permission denied

### ISSUE THREAD

**Issue by jancborchardt** [rmst/yoke#7]
After the seemingly successful installation via pip3 and adding the udev rule I get this:
```
jan@Rechenknecht:~$ yoke
Traceback (most recent call last):
  File "/home/jan/.local/bin/yoke", line 41, in <module>
    dev = yoke.Device(args.name, events=Service.events)
  File "/home/jan/.local/lib/python3.6/site-packages/yoke/service.py", line 67, in __init__
    self.device = uinput.Device(events, name, BUS_VIRTUAL)
  File "/home/jan/.local/lib/python3.6/site-packages/uinput/__init__.py", line 178, in __init__
    self.__uinput_fd = fd or fdopen()
  File "/home/jan/.local/lib/python3.6/site-packages/uinput/__init__.py", line 84, in fdopen
    return _libsuinput.suinput_open()
  File "/home/jan/.local/lib/python3.6/site-packages/uinput/__init__.py", line 70, in _open_error_handler
    raise OSError(code, msg)
PermissionError: [Errno 13] Failed to open the uinput device: Permission denied
jan@Rechenknecht:~$ sudo yoke
[sudo] password for jan: 
sudo: yoke: command not found
```

Any idea?

**Comment by rmst** [comment]
`sudo yoke` didn't work because the `yoke` is only added to path for the user. If you call the script directly it should work using sudo. You can find the scripts location via `which yoke`.

The udev rule didn't seem to work for you. Does it work when you do

```bash
sudo chgrp uinput /dev/uinput # change group
sudo chmod g+rwx /dev/uinput # allow group to read and write
```

?

**Comment by jancborchardt** [comment]
Works with the new install script, thanks a lot!
